version: "3.9"
services:
  api:
    build: .
    container_name: trigger-api
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=development
      - TRIGGER_ENV=development
      - TRIGGER_SECRET_KEY=${TRIGGER_SECRET_KEY}
      - PORT=3333
      - LOG_LEVEL=debug
    volumes:
      - .:/app
      - /app/node_modules