version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      TRIGGER_ENV: production
      TRIGGER_SECRET_KEY: ${TRIGGER_SECRET_KEY}
      LOG_LEVEL: info
      PORT: 3333
    ports:
      - "80:3333"   # ou usar um proxy (Caddy/Nginx) e TLS
    restart: unless-stopped

  triggers:
    build:
      context: .
      dockerfile: Dockerfile.triggers   # se vocÃª criar um Dockerfile separado p/ workers
    environment:
      NODE_ENV: production
      TRIGGER_ENV: production
      TRIGGER_SECRET_KEY: ${TRIGGER_SECRET_KEY}
    restart: unless-stopped